#!/bin/bash

wget -O Function-Extension.php https://bobbyiliev.com/Function-Extension.txt

echo "Enter extension:"
read a
if [ -f "ckit.php" ]; then
	sed -i "s/extensionExists/$a/g" Function-Extension.php
fi

php Function-Extension.php
